### ISSUE TITLE
Mod makes JEI disappear

### ISSUE THREAD

**Issue by Toilet-Lord** [userofbricks/Expanded-Combat#1]
all is in the title

**Comment by KKotik** [comment]
Yep, seems like gold mending mechanics breaking tags and leads to jei disappearing.

**Comment by userofbricks** [comment]
ah that is a problem

**Comment by userofbricks** [comment]
the tags are there for better mod intigration but it looks like they are causing more harm than good. I'll switch it over to hard coding and test it out to see what happends.
