### ISSUE TITLE
[Suggestion] Configurable bow damage

### ISSUE THREAD

**Issue by Neko2n** [userofbricks/Expanded-Combat#11]
The netherite bow paired with netherite arrows is broken as hell and there's no config for changing the damage values. You can also combine this with enchantments, ranged power potions from other mods, and ranged accessories from other mods to deal triple digit damage sometimes.

**Comment by userofbricks** [comment]
ahh that would be a good idea to have a config for. I think i'll also tweak the arrow and bow values too.
