### ISSUE TITLE
[Suggestion] Configurable Gauntlet attributes/stats

### ISSUE THREAD

**Issue by Neko2n** [userofbricks/Expanded-Combat#12]
Gauntlets are a little too overpowered for my pack's scaling, and I also resprited / renamed many of the twilight forest gauntlets to other resources to add my own custom sort of mod compatibility with some other mods in my pack (eg. renaming and respriting the fiery gauntlet to be an ametrine gauntlet for BYG compatibility). Unfortunately, I can't figure out how to change the armor attributes of the gauntlets with Crafttweaker (probably because I'm stupid), so I'm back again to request to make gauntlet stats configurable.

Also, the +5 damage naga gauntlet is EXTREMELY overpowered when paired with a strength II potion and a netherite sword or higher. Even more so with any other mods that affect damage in percents, such as Project MMO's combat stat buff. I ended up doing a total of over 50 damage in one hit with a netherite sword, a strength 2 potion, and level 200 combat in PMMO (+200% melee damage, basically tripling any melee damage.) This would be fine with an 8 damage netherite sword, as that would be 24 damage, but with a 12 damage sword from strength 2 that can hit 36 damage, and with the +5 naga gauntlet damage buff it can raise it to a 17 damage sword, hitting a whopping 51 damage per hit. And that's without enchantments, which scale it even farther.

Sorry if I'm being annoying suggesting all these configurable values. I might be able to figure out how to edit gauntlet attributes myself if it's too much trouble to add to the server config, I'll just need to try harder lol.

**Comment by userofbricks** [comment]
Haha 😂. It’s fine I had been planning on adding a bunch of configuration to the mod at some point. 

If you haven’t already seen I added the bow and arrow configuration in the beta I released yesterday. Hope that it helped you. I might get to this config today but I might just go ahead and add a bunch more as there are a lot of times when this mod can easily get overpowered. Mostly with the mod compatibility options. 

Oh and like last time I might not be able to release it right away.

**Comment by userofbricks** [comment]
And with over 300 lines of code and tens of thousands of characters, gauntlets can now have there armor attributes changed via the server config file.

also on what I said about the other config....... well lets just say I am going to wait till people actualy need it.

**Comment by Neko2n** [comment]
> Haha 😂. It’s fine I had been planning on adding a bunch of configuration to the mod at some point.
> 
> If you haven’t already seen I added the bow and arrow configuration in the beta I released yesterday. Hope that it helped you. I might get to this config today but I might just go ahead and add a bunch more as there are a lot of times when this mod can easily get overpowered. Mostly with the mod compatibility options.
> 
> Oh and like last time I might not be able to release it right away.

Hoping this doesn't reopen the issue, but yes the arrow and bow config helped me LOADS. I've gotten all ranged damage values in my pack back to a normal level, and everything's nice and balanced again. Massive thanks for all of these attribute configs, and it's really nice to see the gauntlet configs too!
