### ISSUE TITLE
[Balance] Great Hammer attack speed - 1.16.5 Beta 2.3.1

### ISSUE THREAD

**Issue by smoothuk** [userofbricks/Expanded-Combat#15]
The Great Hammers have an attack speed of 2.8, making them as fast as daggers but a lot stronger.  One would expect such a big lump of material to be heavy and slow to wield, like 0.5 attack speed or something.

**Comment by userofbricks** [comment]
Oh my I thought I put them as the slowest! That is quite a bit concerning.
