### ISSUE TITLE
Softlock Crashloop after equipping diamond Quiver on server

### ISSUE THREAD

**Issue by Reshirou** [userofbricks/Expanded-Combat#16]
https://paste.shockbyte.com/itaqavekoburiporolez

I equipped a diamond quiver and was instantly kicked from my server. The server itself does not crash however.
Every time I rejoin, I get instakicked again- this log is actually just the whole snippet from rejoin to rekick number 2.
I am effectively softlocked from my own server rn.

**Comment by Reshirou** [comment]
(using Beta 0, 2.3.1)

**Comment by Reshirou** [comment]
it is only in the server environment that this happens, I can equip a diamond quiver in single player
but I did come across a visual bug in single player too which I will post separately lol

**Comment by userofbricks** [comment]
Oh shit. Yeah that is a huge issue. People have been having issues with the quivers on servers. And every time I think I get it fixed something breaks. Your log snippet is very helpful, insightful and informative. Thank you. I will see what I can do to fix this when I get beck home later today.

**Comment by Reshirou** [comment]
Thank you so much for the quick response!

**Comment by userofbricks** [comment]
I think I have this one fixed. I am going to tackle the visual bug you mentioned and then post another beta release. if you still crash with that jar please post another comment here with a log and I'll see what I can do from there.

**Comment by userofbricks** [comment]
I went ahead and uploaded another beta with what I hope will fix this.

**Comment by Reshirou** [comment]
That fixed it! Thank you so much

**Comment by userofbricks** [comment]
awsome! glad to hear it!
