### ISSUE TITLE
Visual Bug with Quiver

### ISSUE THREAD

**Issue by Reshirou** [userofbricks/Expanded-Combat#17]
https://i.imgur.com/n2Y7C1R.png

Arrows rendering the wrong way
I use Magnesium but I tested without that as well, this still happens

**Comment by userofbricks** [comment]
How interesting. They didn’t do that to me when I was Dev-ing I will need to look into this a bit.

**Comment by userofbricks** [comment]
<img width="540" alt="Screen Shot 2021-11-10 at 6 58 22 PM" src="https://user-images.githubusercontent.com/48232299/141223431-cd134a6f-a396-4cc8-beed-beab02081349.png">
hmmm.

are you useing arrows from another mod other than Expanded Combat?

**Comment by Reshirou** [comment]
nope, just flint arrows
I'll go ahead and do some "removing mods one at a time" business to see if I can deduce the exact cause

**Comment by Reshirou** [comment]
Huh, it turned out to be the fault of DefaultEX+, the resource pack
not even a mod conflict

good thing I disabled resource packs first before systematically checking mods, hah
might want to add to the description that DefaultEX+ causes that bug, and close this issue =)

**Comment by userofbricks** [comment]
ah I was getting curios if it was a resource pack. 
I will definetaly add that incompatibility to the mod description.
