### ISSUE TITLE
Client Crash when scrolling through quiver's arrows

### ISSUE THREAD

**Issue by Reshirou** [userofbricks/Expanded-Combat#18]
https://pastebin.com/Ehxz9MJi

**Comment by Reshirou** [comment]
whoops hit send to early on accident
anyway, when scrolling through quiver arrows to swap loaded ones, pressing the left key when on the first arrow seems to cause the crash

it does not crash the server, just the player

it also happens when there's only 2 arrow types and you try to press back

**Comment by Reshirou** [comment]
Also has visual problem where the selected arrow doesnt render; as you can see here the 37 arrow is supposed to be iron and the 20s are two sets of flint, but when selected they dont actually render in the gui
https://imgur.com/a/W9ie66d

**Comment by userofbricks** [comment]
the scrolling problem has beed fixed and released. haven't been able to recreate the render problem though.
