### ISSUE TITLE
Quiver Curios slot disappears if you scroll. 

### ISSUE THREAD

**Issue by nmarshall23** [userofbricks/Expanded-Combat#2]
If your Curios Inventory Screen has a scrollbar, and you scroll down. The contents of the Quiver slot disappears. 
Scrolling up doesn't fix it.
If you leave the scrollbar at the bottom position and close the Curios Inventory Screen, then reopen it the Quiver slot contents are still missing.

To fix it you have to scroll up and close then reopen your Curios Inventory.

**Comment by userofbricks** [comment]
oh my That needs to be fixed!

**Comment by userofbricks** [comment]
@nmarshall23 if you are still watching this Issue: in your personal opinion should the quiver and arrow slots be moved into the curios slot column were the rest of curios slots are?

**Comment by nmarshall23** [comment]
If this is a limitation of curios library, then the best you can do is raise the issue with them.

Maybe hold off changing your code till you hear back from them. 

I like the location of the quiver and arrow slots. It makes it clear that they aren't quite like the other curios slots.

I don't know how curios works, could a curios slot be added after the quiver is equipped? Then you could move quivers to the _back_ or _belt_ slots, and dynamically add an arrows slot.
