### ISSUE TITLE
Suggestion - Support For Epic Fight

### ISSUE THREAD

**Issue by Taknax** [userofbricks/Expanded-Combat#22]
A epic fight mod compatibility would be awesome.

**Comment by userofbricks** [comment]
some resources for when epiuc fight update to mc versions i want to suppot
mod page: [the page](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod)
there data pack page: [adding support](https://github.com/Yesssssman/epicfightmod/wiki/Custom-Weapon-Armor-datapack)
