### ISSUE TITLE
Console issue.

### ISSUE THREAD

**Issue by Taknax** [userofbricks/Expanded-Combat#23]
I have a weird issue in my console. The issue occures for multipble

Here is an example: [https://pastebin.com/qD5C6n21](url)

Here is the full issue: [https://pastebin.com/9z88BxQg](url)

I use the EC 2.4.0-1.20.1-all.jar and Forge 47.1.43.

**Comment by userofbricks** [comment]
hey for some reason your pastebin links aren't working and lead me to a page not found error. could you try redoing them so that I might be able to help?

**Comment by Taknax** [comment]
Ofc.

[https://pastebin.com/0wBaazbM](url)

**Comment by userofbricks** [comment]
ah I see whats going on...
so all of those quote-un-quote errors happen if twilight forest is not installed. however you don't have to install twilight forests as these errors don't effect gameplay or stability of the game. they just mean that some recipes that rely on some items from twilight forest don't load into the game.

sometime soon i hope to be able to move mod specific compatabilities like twilight forest to there own mods. this will get rid of the non game breaking console errors such as these.
