### ISSUE TITLE
Broken Tooltips 1.20.1

### ISSUE THREAD

**Issue by zachsai** [userofbricks/Expanded-Combat#24]
![image](https://github.com/userofbricks/Expanded-Combat/assets/63996164/1932cd5d-aec7-449c-bc87-22efae328575)
Forge 1.20.1
Mod version: 2.5.0

**Comment by userofbricks** [comment]
oh shoot! i'll get on that right away

**Comment by userofbricks** [comment]
tooltips have been fixed in 2.5.1 release
