### ISSUE TITLE
Ignitium shield from L enders cataclysm when used with expanded combat makes the user invincible

### ISSUE THREAD

**Issue by Nov1st2k10** [userofbricks/Expanded-Combat#26]
(the cataclysm server said it was a bug with expanded combat)

I was playing on my friends server, i used my ignitium shield to block an arrow, and then i became an completely invincible, i was unable to die from everything, even /kill

heres the log
https://pastebin.com/4RZQs61Q

**Comment by userofbricks** [comment]
hmmm it is the combination of the two mods that is causing this bug. however i can't tell which mod is causing it. and replicating the bug in a testing environment isn't helping to show me what is going on as all the logs show nothing about any errors or anything. so untill i can see the code for the mod L_Enders Cataclysm i can't help and have to assume the problem has to be in L_Enders Cataclysm.

**Comment by userofbricks** [comment]
I am closing this as not planned due to insufficient ability to find cause of bug. I will also mark the incompatability on curse forge so that others don't run into it
