### ISSUE TITLE
1.16.5 - Mixin Exception

### ISSUE THREAD

**Issue by ToxinZangoose** [userofbricks/Expanded-Combat#27]
Hello, big fan of this mod.

I encountered an issue when initializing the game for 1.16.5.
It appears it has to do with the reach attribute mixin.

Please consider patching this, I love this mod so much.

Below is the log file, I have tried several different versions, including latest.

[latest.log](https://github.com/userofbricks/Expanded-Combat/files/12330667/latest.log)

**Comment by userofbricks** [comment]
looks like you found an incompatable mod. acording to the log you posted the mod in question is Corail Tombstone. As for some reason it seams that Corail Tombstone is modifying the player's reach distance. as I have already dropped support for the 1.16.5 version of this mod the only thing I can do is mark Corail Tombstone as an incompatable mod.

**Comment by Corail31** [comment]
@userofbricks You need to set "require = 0" to "ModifyConstant" in your mixins or you'll get incompatibilities with others mods.
