### ISSUE TITLE
Feature Request - Improve Documentation 

### ISSUE THREAD

**Issue by nmarshall23** [userofbricks/Expanded-Combat#3]
I really impressed with this concept. The Smithing Table is absolutely is underused. 

Currently while I really like the mod, I don't have a firm idea of how good each upgrade is. Eventually I figured how to enhance the shield, but I'm fuzzy on the effects. Each shield upgrade could benefit from an separate name.

Before you add more content to the mod. Please take some time to improve the mod's documentation. This will also help focus your mod. So that new content has a niche to fill. 

Here is an example: [simple-magnets](https://www.curseforge.com/minecraft/mc-mods/simple-magnets), You don't need the banner, or graphic. Just a list of Expanded-Combat's content, what it does and how it works.

If you need help with formatting the mod description I am willing to assist. I can even send you a markdown file to copy into curseforge.

**Comment by userofbricks** [comment]
Oh yeah I have a video in the works that mainly focuses on the shield but it is still being edited as I'm not happy with it yet. I've tried doing descriptions before for other projects of mine (most of which are Discontinued or never got released) but couldn't get the right words in the correct order to make it flow like it should. I'll see what I can do to for now but if there is anything you would like to help improve I will be open for sugestions!
