### ISSUE TITLE
Clash with REI

### ISSUE THREAD

**Issue by HakeemAzma** [userofbricks/Expanded-Combat#32]
Crashes when quiver is equipped in its slot. I believe this is due to the arrow section which pushes REI.
Tested on a clean instance with REI and its addons. Have attached the crash log.

[crash-2023-12-02_06.41.59-client.txt](https://github.com/userofbricks/Expanded-Combat/files/13532454/crash-2023-12-02_06.41.59-client.txt)

**Comment by userofbricks** [comment]
ok. i can try to fix it but due to Schedule stuff, i can't provide compatability with REI however the mod already has perfect compatibility with JEI so until this gets fixed I would suggest using JEI instead of REI.

**Comment by HakeemAzma** [comment]
I noticed that REI itself has many issues that causes crashes. I don't think it has anything to do with yours. At the moment, I've switched to EMI alongside JEI, best setup I've found so far. Thanks.
