### ISSUE TITLE
MC 1.20.1 - EC v3.0.0 crashes when accessing the mod menu

### ISSUE THREAD

**Issue by NovaViper** [userofbricks/Expanded-Combat#33]
Hey I just installed the mod on Minecraft 1.20.1 and when I access the mod config menu with Forge, it instantly crashes the game with the attached: [error.txt](https://github.com/userofbricks/Expanded-Combat/files/13602422/error.txt)

Another thing I noticed is that despite the configs saying that broadswords should be one-handed, in game it says they're two-handed!
![image](https://github.com/userofbricks/Expanded-Combat/assets/7191115/55aafbf3-4db2-4ad5-83ca-f19b3d1ebeb8)

**Comment by userofbricks** [comment]
If you test this with just the mods needed to run EC there is no crash whatsoever. this means there is some sort of conflict between the mods you have instaled and Cloth Config regarding config gui stuff. as I am rather busy with life and updating things I am going to have to let you find out which mods are conflicting. you can do this one of two ways. disableing one mod at a time till you don't have the crash or you can disable half of the mods if the crash still happends then the conflict is withing the half that are still active, and you can repeat the previos step untill you have limited the mods down to the ones causing the issue.

**Comment by userofbricks** [comment]
and i can tell you its not because of anything inside the config.

**Comment by NovaViper** [comment]
Hey I just discovered it's actually an issue with ClothConfig! Found [this issue](https://github.com/shedaniel/cloth-config/issues/229) and went to the previous version of ClothConfig and the crashing went away. Will direct this issue over to them

**Comment by NovaViper** [comment]
> and i can tell you its not because of anything inside the config.

I also was doing testing for the grip type registration/Better Combat integration issue. I noticed Better Combat isn't reguarding the changes to the weapon grip type configs in Expanded Combat at all. I went and changed a couple of other weapons (Cutlass to ONEHANDED, Claymore to ONEHANDED) and Better Combat only assigns them their default grip types (aside from Broad Sword still being TWOHANDED instead of ONEHANDED like it's suppose to be by default). The integration could possibly be bugged somehow? I'm not really sure what it could be since I even went and tried different versions of Better Combat and the same thing still happens

**Comment by userofbricks** [comment]
yeah the onehand/twohand/dualwield thing is purely internal and only for expanded combat. what it is actualy doing is deciding weather or not the weapon has its attributes in the offhand or not. i really need to change that system to match that. originally the two handed weapon was going to completely disable the offhand but there are so many other mods out there that do a better job than i could.

**Comment by NovaViper** [comment]
> yeah the onehand/twohand/dualwield thing is purely internal and only for expanded combat. what it is actualy doing is deciding weather or not the weapon has its attributes in the offhand or not. i really need to change that system to match that. originally the two handed weapon was going to completely disable the offhand but there are so many other mods out there that do a better job than i could.

Ah that explains why it's not matching up to what Better Combat has. Yeah integrating with mods like Better Combat would be a good option since they handle that seamlessly imo. I'm unsure of how to implement the API for that but looking over at [Simply Swords](https://github.com/Sweenus/SimplySwords) would be a nice a place to start 🤔
