### ISSUE TITLE
Game Crash - Expanded combat 3.0.2

### ISSUE THREAD

**Issue by YejiYeah** [userofbricks/Expanded-Combat#34]
Hi,

I have been using this mod in my modpack, however in the last update there is a crash when just start the game in the loading screen.

Please find below latest.log and crash report:

[latest.log](https://github.com/userofbricks/Expanded-Combat/files/13722738/latest.log)

[crash-2023-12-19_21.55.47-client.txt](https://github.com/userofbricks/Expanded-Combat/files/13722739/crash-2023-12-19_21.55.47-client.txt)

**Comment by userofbricks** [comment]
It apears to be an issue regaurding repair ingrediant registry. I has uploaded a fix on EC Cj's Gilded Netherite Compat that seems to work. It will be live on curseforge as soon as the thier bots give it the go ahead. but you can download it right now from Modrinth [here](https://modrinth.com/mod/ec-cjgn-plugin/version/bDx8pZA8).

**Comment by YejiYeah** [comment]
Thank you so much!, by the way, I love the mod a lot
