### ISSUE TITLE
Netherite upgrade weapons recipes are not working

### ISSUE THREAD

**Issue by YejiYeah** [userofbricks/Expanded-Combat#35]
Dear UserOfBricks,

The netherite weapons' recipes are not working, I took a look in the config files however I couldn't find anything, could you please help?,

![image](https://github.com/userofbricks/Expanded-Combat/assets/77309538/abd3b065-3200-4878-bcd5-b54c9e56a9d2)

Thank you, 
Regards
Sarah

**Comment by userofbricks** [comment]
what on earth! I'll take a look.

**Comment by userofbricks** [comment]
this will be fixed in EC 3.0.4
