### ISSUE TITLE
Crash when upgrading shields with apotheosis

### ISSUE THREAD

**Issue by YejiYeah** [userofbricks/Expanded-Combat#37]
Hi UserOfBricks

I got this crash when trying to add gems to the shields using the smithing table:

[latest.log](https://github.com/userofbricks/Expanded-Combat/files/13758006/latest.log)

[crash-2023-12-22_22.26.24-client.txt](https://github.com/userofbricks/Expanded-Combat/files/13758007/crash-2023-12-22_22.26.24-client.txt)

![crash1](https://github.com/userofbricks/Expanded-Combat/assets/77309538/b1840850-246b-4edf-a7cc-be4a71821218)

Please let me know if you need more details.

Thank you,
Regars
Sarah

**Comment by userofbricks** [comment]
nope this is the third time today someone has reported this bug and I am already working on it and I think I have fixed it. just need to do some testing and locating of some other bugs and there will be a realease.

**Comment by userofbricks** [comment]
this will be fixed in 3.0.4
