### ISSUE TITLE
There is a problem with the agility effect.

### ISSUE THREAD

**Issue by jjuan1005** [userofbricks/Expanded-Combat#38]
I took off my armor with agility, but the effect doesn't go away. Drinking milk won't solve it.

**Comment by userofbricks** [comment]
this should have been fixed in EC 3.0.3, are you using a version before that?

**Comment by jjuan1005** [comment]
Yes. I was using 3.0.1. After installing 3.0.4, the problem that occurred before was solved. However, wearing helmets, armor, and leggings doesn't get faster, but I think only shoes get faster. Is that how it's supposed to be?

**Comment by userofbricks** [comment]
no it's not supposed to get faster and faster. are the shoes still doing it?

**Comment by userofbricks** [comment]
i've done some extensive testing for it and it is not happening in EC 3.0.4

**Comment by jjuan1005** [comment]
The phenomenon of getting faster has disappeared. 
but the Agility ability applies only to shoes and does not make other equipment faster.
