### ISSUE TITLE
Crash when equipping Gauntlets from Twilight Forest  

### ISSUE THREAD

**Issue by YejiYeah** [userofbricks/Expanded-Combat#39]
Hi!,

The game crashes when I equipped the knight gauntlet from Twilight Forest:

[latest.log](https://github.com/userofbricks/Expanded-Combat/files/13759126/latest.log)

[crash-2023-12-23_07.05.54-client.txt](https://github.com/userofbricks/Expanded-Combat/files/13759131/crash-2023-12-23_07.05.54-client.txt)

Thank you,
Regards
Sarah

**Comment by userofbricks** [comment]
have you changed the equip sound for any materials? I can't reproduce this bug at all even in a instance with only the required mods for EC and the twilight plugin.

**Comment by YejiYeah** [comment]
I tried with all other gauntlets from the EC and other mods and they have no issues, I just noticed that all of them have their sound when equipping them, I cannot find the reason this happens, I am playing in the modpack I made to play with my friends, could you test if there is an incompatibility issue with other mod?, the modpack is: https://www.curseforge.com/minecraft/modpacks/yes-nicer-mc-forge-1

Thank you!

**Comment by userofbricks** [comment]
if the modpack was less than 50 mods I might do it but that one is 300+ mods. due to my schedule and family holiday plans I can't find it in that quantity of mods. especialy since there is no issue when only the required mods are loaded.

**Comment by userofbricks** [comment]
I'm going to close this until the incompatible mods are found
