### ISSUE TITLE
Instance not loading (close) when using EC Aquamirae Compat mod

### ISSUE THREAD

**Issue by YejiYeah** [userofbricks/Expanded-Combat#40]
When I run MC with other mods having Aquamirae Compat mod installed, the game stop loading and closes, I don't get a crash report and the Latest logs doesn't contain enough information, I wonder if there is a incompatibility with other mod I have in the modpack I am using: https://www.curseforge.com/minecraft/modpacks/yes-nicer-mc-forge-1

[latest.log](https://github.com/userofbricks/Expanded-Combat/files/13760321/latest.log)

Thank you!

**Comment by userofbricks** [comment]
that would be some other mod creating that issue perhaps there is another mod creating it. oh and even if Aquamirae Compat is the only mod you add and then the error occurs there is no garentee it is the mod creating the issue.
