### ISSUE TITLE
Gauntlets and quivers supposedly not equiping

### ISSUE THREAD

**Issue by PrinceAbsolution** [userofbricks/Expanded-Combat#41]
I have found the culprit! It is the enderite plugin fro EC that is causing the curios issue.

_Originally posted by @PrinceAbsolution in https://github.com/userofbricks/Expanded-Combat/issues/36#issuecomment-1868436304_

**Comment by PrinceAbsolution** [comment]
It actually appears that all the plug ins cause curios to not work.

**Comment by userofbricks** [comment]
how exactly did you come to this conclusion? i've tested every plugin with only the required mods on thier latest versions and none of them had an issue with having gauntlets equiped.

**Comment by userofbricks** [comment]
I'll leave this open, but I don't know how you are even comming across this bug unless the bug is on curios's side. or you are using outdated versions of all the mods.

**Comment by PrinceAbsolution** [comment]
I tested them on my modpack and independently and the gauntlets and quivers refuse to work.

**Comment by PrinceAbsolution** [comment]
i just fired up a new fresh version and encountered the same issue.

**Comment by PrinceAbsolution** [comment]
Im also using the latest versions.

**Comment by PrinceAbsolution** [comment]
![image_2023-12-28_172429152](https://github.com/userofbricks/Expanded-Combat/assets/154634422/35d2f260-fa75-4968-80f5-79e76518842c)
mod list
![image_2023-12-28_172454273](https://github.com/userofbricks/Expanded-Combat/assets/154634422/c4c178ac-2845-4b72-b3f2-c36954d7954d)
issue

**Comment by userofbricks** [comment]
interesting. well then I am going to go through all the plugins and see if I can get the same thing to occur. I just tested with the twilight forest plugin and everything is working flawlessly, but I will check others

**Comment by PrinceAbsolution** [comment]
Sorry to cause you all this trouble over the holidays

**Comment by PrinceAbsolution** [comment]
the enderite and cataclysm are the ones i tested

**Comment by userofbricks** [comment]
really. I just tested the plugins for CJ's gilded netherite and CJ's enderite and all gauntlets and quivers are still working and able to be equiped.

**Comment by PrinceAbsolution** [comment]
Well i have no clue. I showed you the mods i have installed and the issue i have. perhaps it could be a config error or something? Im using the curse forge versions of both so maybe modrith doesnt have this issue.

**Comment by userofbricks** [comment]
When I checked both the gilded netherite and enderite i did them at the same time. I just tried the enderite plugin on its own like you did and behold the Issue was there.

**Comment by userofbricks** [comment]
now I just need to figure out why

oh and i checked the cataclysm plugin and it works fine on its own

**Comment by PrinceAbsolution** [comment]
Don't worry about the cataclysm one it was curseforge launcher glitching out and having the enderite one installed even though it wasn't appearing in the list.

**Comment by userofbricks** [comment]
ah that must be anoying

**Comment by PrinceAbsolution** [comment]
Curseforge launcher L

**Comment by userofbricks** [comment]
man I just figured out what is going on. I tried to keep the default compatability that CJ's enderite has with his gilded netherite mod and that ment adding the gilded enderite gauntlets and quivers to thier respective item tags that curios requires in order to put the items into the slots. however with how minecraft/forge load tags if any item in a tag doesn't exist it won't load the tag. that means that if the gilded netherite mod is not instaled no gauntlet can be equiped.

**Comment by userofbricks** [comment]
I'm gona have to change a bunch of things to get this actually working again.

**Comment by userofbricks** [comment]
maybe not as much as I thought. I should be able to get a working version out today

**Comment by userofbricks** [comment]
okay I have uploaded a new version of the enderite plugin on both curseforge and modrinth. the one on curseforge will be available whenever the curseforge bot approves it.

**Comment by PrinceAbsolution** [comment]
thank you so much
