### ISSUE TITLE
re-enter the game, the arrow is not in the quivers

### ISSUE THREAD

**Issue by zhenadao** [userofbricks/Expanded-Combat#44]
I have put the arrow in quivers, but when I re-enter the game, arrows will be in the inventory instead of the quivers.

mod version: expanded_combat-1.20.1-3.0.5-all.jar
Forge: 47.2.19

**Comment by userofbricks** [comment]
what on earth! another bug that doesn't show up in the dev environment but for some reason shows itself only outside it.

I'll look into it but bugs that exibit this kind of behavior often are not easy to fix.

**Comment by userofbricks** [comment]
no mention of anything in logs so its gonna take a while to figure out what is going on.

**Comment by gunnartom** [comment]
I am having the same problem. I've found that if your inventory is full it has nowhere to go so it stays in the quiver. 

Mod Version: expanded_combat-1.20.1-3.1.2-all
Forge: 47.3.5

![Screenshot 2024-08-12 135741](https://github.com/user-attachments/assets/8a243732-954c-4ede-b705-d1233411165b)
![Screenshot 2024-08-12 135839](https://github.com/user-attachments/assets/a69ccbb1-9c29-478f-b072-eb33ee0a17b1)

**Comment by AGkizlis** [comment]
I've been having this issue for a long time, and I came here looking for a solution... Seems I'll have to wait for it. Meanwhile, I'll look for a quiver from Supplementaries mod.

**Comment by userofbricks** [comment]
there is now a fix for this in the latest update of EC. I moved the quiver storage to a bundle like system. this issue no longer exists.
