### ISSUE TITLE
quiver, enchantments, other weapons

### ISSUE THREAD

**Issue by CACOKKOTA** [userofbricks/Expanded-Combat#45]
Hi! I would like to see some changes with enchantments in EC and some weapons, because currently they're too OP (1.20.1)

mod version 3.0.5

**Agility** 

too fast, +100% movement speed for 1 lvl enchantment and 200% for 2nd is too much, it'll be better to spread this enchantment on 5 levels where max lvl will give +100% to make it less OP (or make max speed configurable)
i obtained this book like in fisrt dungeon in my modpack and only elytras will be faster than this :/

**knockback resistance**

downgrade to 4 levels and max +4 knockback resistance (so in normal conditions full netherite + max lvl knockback(KB) on netherite gauntlets resistance will only give 90% KB resist
this enchantment (at current moment) is too OP, even zombie with level 100 knockback can't move me when i'm wearing only gauntlet with max enchantment

**Katanas and blocking**

Currently, katanas block more than 2 arrows (without ench) so blocking enchantment doesn't work at all (or i don't get how it really works)

**scythes and potions**

well, pretty good for endgame, but infinite uses of potions on the scythe is dumb i guess, shouldn't potions have it's own durability on scythes( like some part of potion staying inside of attacked entity)? like 200 for 1 lvl potions and 90 for 2nd lvl potions (make it switchable in config pls)
also potion's duration is multiplied by 2 so instead of damaging with wither 2 potion for 22 secs i get 44 secs
multiplier should be 0.75-0.5 if potions durability mechanic is not possible

**quivers**
![image](https://github.com/userofbricks/Expanded-Combat/assets/113460989/40a52a73-2b69-49d2-bd09-b4b6cb3a19d2)
arrows slot is blocked with potions

**new gauntlets**
currently, it's impossible to craft some gauntlets because of craft similarity of gauntlets
guess some other items should be added for some crafts (for maulers leather, for fighters bindings red dye, something like that)
![image](https://github.com/userofbricks/Expanded-Combat/assets/113460989/c657cce0-9988-48e1-9b7a-0bbe1c9886c5)

**soul fists**
i don't get it, why they are so expensive? 3 netheringots and having same stats, maybe add such craft: 7 gold ingot, diamond middle top and netherite gauntlets in the middle of the crafting grid?
and i don't understand what is happening here:
you trying to make gauntlets trimmable and this crafts currently are fillers?
![image](https://github.com/userofbricks/Expanded-Combat/assets/113460989/9d828821-63a1-4b99-a621-14e6dfda23f5)

**Comment by userofbricks** [comment]
- the agility enchant has needed balancing for a while, but I was under the impresion it was increasing things by 10% each lvl not 100%. boy that needs to change. 
- As for the knockback resist I do need to change that. the numbers for it are not very informative in the code.
- katana blocking with enchantment increases the number of arrows that are blockable in a row. I have done extensive testing on this in its creation and it is working as intended.
- making the potions on scythes limited use has been in thebackofmy mind for months now. I ust haven't given time to it yet with all the compatability mods/plugins ive been creating lately.
- The potions covering the quiver inventory definetally needs fixing. probably move them over for now.
- the maulers, gauntlet and soul fist gauntlets are not supposed to be craftable. they are treasure items. thanks for telling me about this bug.

**Comment by userofbricks** [comment]
all armor trim recipes JEI shows end up with the iron armor, so that is a JEI bug. the recipes to trim everying still work.

**Comment by userofbricks** [comment]
these issues have now been fixed and the fixes will come out in the 3.1.0 update
