### ISSUE TITLE
[1.20.1] Ars Expanded Combat Compat - Enchanter's weapons do not trigger spells

### ISSUE THREAD

**Issue by JackTheRedCreeper** [userofbricks/Expanded-Combat#46]
(Posting here since there's no github page for Ars Expanded Combat Combat)

I made a enchanters glaive and gave it hurt -> amplify, but when used the chat says that "The spell does not start with a form glyph" (as if trying to fire the spell from the book). The same spell combination works with a standard Ars Nouveau sword, and giving the glaive a spell with a form glyph doesn't work.

Tested with other weapons (broadsword, battle staff) and they don't trigger spells either.
Better Combat is on but shouldn't affect it.

**Comment by userofbricks** [comment]
Interesting I'll have to take a look at this.

**Comment by userofbricks** [comment]
i have now fixed this in the latest update

**Comment by JackTheRedCreeper** [comment]
Thanks, I'll give it a try

**Comment by JackTheRedCreeper** [comment]
Late update, but yep, works perfectly, thanks!
