### ISSUE TITLE
Issue with EC Aquaculture and EC Blue Skies.

### ISSUE THREAD

**Issue by PercyJames** [userofbricks/Expanded-Combat#47]
[launcher_log.txt](https://github.com/userofbricks/Expanded-Combat/files/14119688/launcher_log.txt)

According to some people I talked to your Aqua Culture and Blue Skies addons are conflicting for some reason.

**Comment by userofbricks** [comment]
dang. probably forgot to rename the directory holding the code for one of the mods.

**Comment by PercyJames** [comment]
thanks for reading
