### ISSUE TITLE
Incompatible Addons

### ISSUE THREAD

**Issue by DoctorEclipse44** [userofbricks/Expanded-Combat#48]
EC Aquaculture and EC Aquamirae do not work together, and crash in the same manner as #47 
I remember the Epic Samurai addon giving the same issue with another addon. i think it **may** have been EC Ars Noveau, but my memory isn't very good and my computer is having issue right now so i can't check.

Please check through your mods when you have time, this is a repeating problem across many of them.

**Comment by userofbricks** [comment]
finished and fixed
