### ISSUE TITLE
Move dealing extra damage from LivingAttackEvent to LivingTickEvent

### ISSUE THREAD

**Issue by lcy0x1** [userofbricks/Expanded-Combat#49]
In this file https://github.com/userofbricks/Expanded-Combat/blob/forge-1.20.1/src/main/java/com/userofbricks/expanded_combat/events/GeneralForgeEventBusEvents.java

I find that you deals extra damage for various different elements. However, since it's in `LivingAttackEvent`, it means that those damage will be processed before the actual melee damage, causing problems with other mods.

The recommended way is that in `LivingHurtEvent`, you record it and add it to a delayed-processing list, which will be executed in server tick event. By doing this, you can make sure that your damage is processed after the melee damage. Additionally, you should make your own damage type and tag them as `BYPASS_COOLDOWN` to bypass iframes. Altering invulnerableTime is not a good idea

To implement the delayed-processing list, you just need to declare `static List<Runnable> LIST`, wrap your code in `LIST.add(()->{...})`, and then in server tick event, do `LIST.forEach(Runnable::run)` and `LIST.clear()`

**Comment by lcy0x1** [comment]
Also add those damage types to `AVOID_THORNS` and check for this tag in your attack event to prevent loop. Don't rely on recursion.

**Comment by userofbricks** [comment]
moving to this method in 3.1.1
