### ISSUE TITLE
Crashes when reforging new weapons with modifier mod

### ISSUE THREAD

**Issue by ConqAra** [userofbricks/Expanded-Combat#5]
When you use the smithing table, the modifier mod allows you to reforge your items in a different section of it. when trying to do that with any new items from your mod, it crashes.

Modifier mod: _https://github.com/CursedFlames/Modifiers/_

**Comment by userofbricks** [comment]
@ConqAra this may not be fixable from my end. but I can't even tell unless you attach a crash log/report.
