### ISSUE TITLE
Crash when putting quiver in quiver curio slot

### ISSUE THREAD

**Issue by abby-cadabra** [userofbricks/Expanded-Combat#50]
Hi there,

Can't be certain of the cause, but I've identified a repeatable crash when I try to put the standard EC Quiver item into the quiver slot.

Minecraft Version 1.20.1
Forge
Expanded Combat 3.1.0
Curios API 5.7.0

Crash log is attached.

[crash-2024-03-01_12.17.59-client.txt](https://github.com/userofbricks/Expanded-Combat/files/14455264/crash-2024-03-01_12.17.59-client.txt)

Happy to provide any other info as needed.

**Comment by abby-cadabra** [comment]
Can confirm that switching from REI to JEI solves the crash.

**Comment by userofbricks** [comment]
at this point adding REI Specific support is outside what I have time for.
