### ISSUE TITLE
Enderite plugin doesn't let the mod load

### ISSUE THREAD

**Issue by PrinceAbsolution** [userofbricks/Expanded-Combat#51]
Minecraft Version: 1.20.1

Forge Version: 47.2.0

Other mods loaded: dependencies

**Comment by userofbricks** [comment]
log or crash log is needed for the problem to get fixed

**Comment by userofbricks** [comment]
I can't replicate this issue. and due to inactivity I am closing this thread

**Comment by PrinceAbsolution** [comment]
My apologies as I was away on vacation
[crash-2024-03-16_13.25.07-fml.txt](https://github.com/userofbricks/Expanded-Combat/files/14625190/crash-2024-03-16_13.25.07-fml.txt)
