### ISSUE TITLE
[Suggestion] add back invincibility frames

### ISSUE THREAD

**Issue by nerdman0** [userofbricks/Expanded-Combat#52]
The mod currently removes invincibility frames, making the combo of gauntlets + autoclicker result in insanely high dps. I think there should be a config option to control whether the mod removes i-frames.

**Comment by userofbricks** [comment]
the mod doesn't remove i frames unless it is the specific dmg types that are not available on craft-able items. now I do intend to change this way of implementing multiple dmg types on one item but it shouldn't be removing all i-frames.

**Comment by nerdman0** [comment]
I downloaded just this mod and it still removes I-frames, so I guess its a bug,

I recorded this video using only the latest version of expanded combat for 1.20.1 (or at least the latest available on curseforge) and its dependencies. I managed to kill in iron golem near instantly using only the gauntlets in my curios slot and an autoclicker.

I'm going to upload a video showcasing this soon, but the file is too large for a comment on github (why is the size limit 10MB anyway)

**Comment by nerdman0** [comment]
https://youtu.be/g9aSzX0j8oQ

**Comment by userofbricks** [comment]
hoping that moving to the method mentioned in issue #49 will fix this issue. should be out in the upcoming 3.1.1 update. I have a few other bugs/inconsistencies I want to look at before publishing it.

**Comment by userofbricks** [comment]
closing this issue for now
