### ISSUE TITLE
Re: Enderite Plugin Issue 

### ISSUE THREAD

**Issue by PrinceAbsolution** [userofbricks/Expanded-Combat#53]
Minecraft Version: 1.20.1

Forge Version: 47.2.0

Other mods loaded: dependencies

Log
[crash-2024-03-16_13.25.07-fml.txt](https://github.com/userofbricks/Expanded-Combat/files/14643484/crash-2024-03-16_13.25.07-fml.txt)

**Comment by userofbricks** [comment]
it would seem as though CJ's Enderite has changed its code structure. if you use a prior version of it this should resolve itself I'll get to updating the enderite plugin soon.

**Comment by userofbricks** [comment]
was fixed in the 1.2.0 release
