### ISSUE TITLE
1.20.1 Remove specific weapons? [question]

### ISSUE THREAD

**Issue by FruitloopMcGee** [userofbricks/Expanded-Combat#54]
Hi
While playing on a heavily modded custom pack it seems whenever someone mouses over an Iron_Katana weapon they hard crash out of minecraft. 
I don't expect you to track this down for me or anything, just wondering if there is a way to disable the katana or at the least the Iron_Katana item from spawning in the game?
Thanks

**Comment by userofbricks** [comment]
currently their is no way to disable a specific item without the use of external mods such a KubeJS or Craft tweaker.
