### ISSUE TITLE
[Worker-Main-9/WARN] [minecraft/ModelManager]: Missing textures in model expanded_combat

### ISSUE THREAD

**Issue by daniel840711** [userofbricks/Expanded-Combat#55]
https://mclo.gs/bHKPGN5
Hello userofbriks,

- **Minecraft Version**: 1.20.1
- **Mod Version**: [expanded_combat-1.20.1-3.1.1-all.jar]
- **Forge/Fabric Version**: [forge 1.20.1  47.2.20]
- **OS**: [win11]

The expected outcome is for all items/blocks to display their textures correctly. However, the affected elements appear invisible or with a missing restarting the game and reinstalling the mod, but the issue persists. No error messages are displayed, suggesting the game isn't recognizing the texture files for these specific items/blocks.

This occurs during both gameplay and in the inventory screen. Unfortunately, I'm not using any other mods that could potentially conflict with this one, to my knowledge.

I appreciate your work on this mod and hope this report helps in pinpointing and resolving the issue. Thank you for your attention to this matter.

**Comment by DrThraxGLA** [comment]
it just not expanded_combat-1.20.1-3.1.1-all.jar but ec_es_plugin-1.20.1-1.1.1-all.jar, ec_aquaculture_plugin-1.20.1-1.1.0-all.jar and ec_create_plugin-1.20.1-1.1.1-all.jar that missing textures

**Comment by deaver812** [comment]
After troubleshooting my mod list I personally found that this error was caused by the mod "Dynamic Trim" and removing it solved the issue.

**Comment by userofbricks** [comment]
yeah the issue isn't with expanded combat. I have tested every single combination of it and the compatibility mods and there are not texture errors. Iv'e even test both in the development environment and in the user facing modded environment and still nothing.

**Comment by daniel840711** [comment]
I appreciate the effort you took to review my issue and provide a detailed and effective solution.
