### ISSUE TITLE
fps drop with shield

### ISSUE THREAD

**Issue by empror20** [userofbricks/Expanded-Combat#57]
Minecraft Version: 1.20.1.
Forge Version: 47.2.0.
mod version: expanded_combat-1.20.1-3.1.1-all.jar.
issue: fps drop when using, have it in inventory or even pass over it modded shield (all shields).
extra info: I usually play with shaders with around 50-60 fps max.

without:
![no shield](https://github.com/userofbricks/Expanded-Combat/assets/167574100/13fb93ac-fcbd-4b65-b50a-7f74f39692af)
with(inventory):
![inventory shield](https://github.com/userofbricks/Expanded-Combat/assets/167574100/67545f76-bc55-4f5d-b582-4f90e14fe49c)
with:
![using shield](https://github.com/userofbricks/Expanded-Combat/assets/167574100/e73b539f-5541-4b1b-9666-678af7c7ad5b)

**Comment by userofbricks** [comment]
interesting. I wish I was more knowledgable about model rendering. cause the shield renderer uses five entity model layers to render and that is probably the cause. but as of right now I don't have a way of doing it differently.
