### ISSUE TITLE
shield not blocking when damaged

### ISSUE THREAD

**Issue by OrangeSniper** [userofbricks/Expanded-Combat#58]
the shield blocks properly when at full durability but the moment it takes damage it fails to block any damage

**Comment by OrangeSniper** [comment]
On further testing, it properly blocks projectiles. No damage is done when the shield is up but it doesn't make any sounds or animations and it damages my armor

**Comment by OrangeSniper** [comment]
Here is a [video](https://drive.google.com/file/d/1-fPQMqFnjS5ArhW9tl1xc4wkvm6uKsiC/view?usp=sharing) that shows the evidence and examples

**Comment by userofbricks** [comment]
By default the mod makes shields have a chance to block based on the percentage of durability left. So at 90% durability the shield will block 90% of the time. If you don’t like it this way there are other blocking options in the config including the way vanilla does it.

**Comment by OrangeSniper** [comment]
Had no idea this was a feature. Thank you
