### ISSUE TITLE
Curios and REI hate this mod.

### ISSUE THREAD

**Issue by MagmaSlime123** [userofbricks/Expanded-Combat#62]
Title, report and mod list below.

https://pastebin.com/9Y1t0p3p

**Comment by userofbricks** [comment]
Curios doesn’t hate the mod it’s just rei. And this is an issue on the side of reí not implementing JEI’s plugin stuff correctly. And as I have a busy schedule I am only gonna support JEI since it is on fabric as well as forge and neoforge.
