### ISSUE TITLE
Alex's Caves plugin gauntlet tag issue

### ISSUE THREAD

**Issue by ThePiekar** [userofbricks/Expanded-Combat#64]
Alex's caves plugin seems to list gauntlets in a broken way (eg. tough_hide instead of tough_hide_gauntlet) (also listing tough_hide twice, not sure if its an issue though), making all gauntlets lose the tag.

(Sorry for the unending issues, if the playtesting is not welcome, feel free to let me know)

**Comment by Mi6kbuttface** [comment]
I'd like to addon to this report by reporting that with the Alex's caves compact enabled, all trim recipes fail to generate and you cannot use trims in a smithing table at ALL

**Comment by userofbricks** [comment]
i have a feeling this is the cause of #65

**Comment by userofbricks** [comment]
ended up being a quick fix will be corrected in the 1.0.6 release
