### ISSUE TITLE
Alex's Caves Trim Recipe Missing

### ISSUE THREAD

**Issue by Mi6kbuttface** [userofbricks/Expanded-Combat#65]
With your compat addon for Alex's caves, armor trimming and all smithing table functions go missing from the recipes
![image](https://github.com/userofbricks/Expanded-Combat/assets/71010323/be95a411-7be5-4a79-8f1a-d2a413f244b4)
![image](https://github.com/userofbricks/Expanded-Combat/assets/71010323/b4750e9c-ff23-4d3b-b587-48588941d485)
![image](https://github.com/userofbricks/Expanded-Combat/assets/71010323/fefb513f-2818-41e6-b4d4-36fa7c7300fd)

**Comment by userofbricks** [comment]
hmmm I wonder why I don't change anything specific with smithing in that addon. but I will look into it when I have time.

**Comment by userofbricks** [comment]
ended up being a quick fix regaurding tag related to #64 will be corrected in the 1.0.6 release
