### ISSUE TITLE
No curious window. ("SOLVED?")

### ISSUE THREAD

**Issue by HappyPdev** [userofbricks/Expanded-Combat#67]
I was editing the configuration, and as I have other mods that implement other quivers, I decided to disable it. This made the curious window not open again. I don't know if it's because of interaction with other mods, but I reproduced the problem this way, and by re-enabling it, the window was back to normal.

I'm telling you this in case it's something unknown to fix or change.

Best regards and great mod and addons.

**Comment by userofbricks** [comment]
that's good to know I probably forget to not put the quiver slot in the quiver menu when quivers get disabled thus casing the menu to error and not open.
