### ISSUE TITLE
Apotheosis Plugin Crashing Game

### ISSUE THREAD

**Issue by snixton** [userofbricks/Expanded-Combat#68]
I've updated Apotheosis to the latest version (7.4.0) and after a few testing, I've found that Apotheosis plugin is causing the game to crash on startup. I've pasted my crash log to see what is causing the issue
[crash-2024-07-09_14.23.15-client.txt](https://github.com/user-attachments/files/16138998/crash-2024-07-09_14.23.15-client.txt)

**Comment by userofbricks** [comment]
well thats not good to hear. Apotheosis does update quite frequently so its not surprising that something broke.

**Comment by userofbricks** [comment]
just uploaded a fixed version to the modpages
