### ISSUE TITLE
[Issue] Unable to change Quiver hotkeys

### ISSUE THREAD

**Issue by ShinryuAspect** [userofbricks/Expanded-Combat#69]
I may be blind, but I am unable to find anywhere on the Controls a reference to the Quiver slot cycling hotkeys. As stated in the Curseforge page, those keys are Z and X, which clearly seem to work and correctly cycle through, but in heavy modded environments, it's a pain not being able to confugire the Hotkeys.

EDIT: while playing, I also noticed anoether minor thing: it seems the arrows from the Quiver are unequipped whenever I join the world, even tho the Quiver stays on the slot.

**Comment by userofbricks** [comment]
hmm. They should be listed in the key binds page. I'll give it a look but I am rather busy at the moment so it could be another week or two before I can get to it.

**Comment by gunnartom** [comment]
Same problem as of today.

Mod Version: expanded_combat-1.20.1-3.1.2-all
Forge: 47.3.5

**Comment by userofbricks** [comment]
I was able to find the issue. turns out forge changed the event for registering they key binds from a forge sided vent to a mod specific event. thus causing weirdness. this has been fixed in the latest version of EC.
