### ISSUE TITLE
Crash when tipping vanilla/flint arrows in Fletching Table

### ISSUE THREAD

**Issue by Reshirou** [userofbricks/Expanded-Combat#7]
https://pastebin.com/SnnHrbRK

Crash Report

Might as well also add the Fletching Table UI text is off center

**Comment by Reshirou** [comment]
https://pastebin.com/PGCxrA1H

Here is a cleaner crash report.

Also, Flint Arrows don't actually have a new texture, just a new name. I'm sure you knew this one but just putting it out there anyway.

**Comment by userofbricks** [comment]
I found the bug. It will be apart of the next release.
