### ISSUE TITLE
EC Epic Samurai Compat not compatible with Samurai Dynasty

### ISSUE THREAD

**Issue by DoctorEclipse44** [userofbricks/Expanded-Combat#71]
The add-on for ["Epic Samurai"](https://wwwcurseforge.com/minecraft/mc-mods/ec-epic-samurai-compat) no longer works as epic samurai has rebranded to [Samurai Dynasty.](https://www.curseforge.com/minecraft/mc-mods/samurai-dynasty)
The addon does not detect the mod under the new name in any capacity.

**Comment by Diamon-sword1** [comment]
i have this issue too, the epic samurai is now samurai dynasty or something like that, name change most likely broke it

**Comment by userofbricks** [comment]
Yeah it was. Just got an update for that out yesterday.
