### ISSUE TITLE
Default Curios GUI does not open with this mod installed

### ISSUE THREAD

**Issue by bred-and-butter** [userofbricks/Expanded-Combat#74]
MC version: 1.20.1
Forge version: tested on 47.3.10, 47.3.7, 47.3.0, 47.2.20

I was using this mod with no problems, but then, I do not know why, maybe something was updated and i did not notice or do not remember updating, but i no longer could open the curios slots UI

![image_2024-09-30_235654523](https://github.com/user-attachments/assets/46cbf548-c6bd-4813-8fbc-1fbe868a732e)

The one that opens by clicking this button. The keybind also did not work.

Also holding items with the mouse and left clicking on that icon made the item completely vanish.

I really like this mod, but cant really use it in my modpack with this bug :/

Edit:
Forgot mod versions
EC 3.2.1 and 3.1.2
Curios 5.10.0

**Comment by userofbricks** [comment]
It looks as though curios had a recent update. EC 3.2.1 for MC 1.20.1 supports curios 5.9.0 but it might not support 5.10.0 yet.

**Comment by userofbricks** [comment]
EC 3.1.2 for MC 1.20.6 support Curios 8.0.0

**Comment by adamk33n3r** [comment]
EC 3.2.1 also not working on mc 1.20.1 curios 5.9.0. We updated EC so that the arrows wouldn't keep dropping but now we can't even equip the arrows.

Was working on EC 3.1.2

![image](https://github.com/user-attachments/assets/fdb6584d-6397-4ad5-b139-adc441f364b9)
Here is what happens when I open the curios gui. I can see the slot for the quiver itself, but the quiver slots don't show up on the right.

**Comment by adamk33n3r** [comment]
After reading this issue again, it looks like it is perhaps a different issue. Didn't realize OP couldn't open the GUI at *all*. I can make a new issue if needed.

**Comment by userofbricks** [comment]
oh shoot! sorry @adamk33n3r I didn't see your post. To get rid of the arrows dropping I had to make quivers act like bundles. Just grab a stack of arrows and click on your quiver and the arrows should go into the quiver.

**Comment by adamk33n3r** [comment]
> oh shoot! sorry @adamk33n3r I didn't see your post. To get rid of the arrows dropping I had to make quivers act like bundles. Just grab a stack of arrows and click on your quiver and the arrows should go into the quiver.

Oh! OK, that makes sense. I was so confused 😂

**Comment by userofbricks** [comment]
the original issue has been fixed and will come out with release 3.2.3
