### ISSUE TITLE
1.21 Neofroge?

### ISSUE THREAD

**Issue by IvoryJustie** [userofbricks/Expanded-Combat#75]
You can use these curios instead
https://www.curseforge.com/minecraft/mc-mods/curios-continuation
&
https://www.curseforge.com/minecraft/mc-mods/adorned

**Comment by userofbricks** [comment]
oh thanks, I did notice curios wasn't gonna update, and I have been planing to update to 1.21.2 neoforge when it comes out.

**Comment by IvoryJustie** [comment]
> yea for some reason i think reg curious is gonna stop doing updates

**Comment by IvoryJustie** [comment]
Also this mod 
https://www.curseforge.com/minecraft/mc-mods/accessories
