### ISSUE TITLE
game crashes when using ec epic fight compat

### ISSUE THREAD

**Issue by WobblyDynamite5462** [userofbricks/Expanded-Combat#77]
the game crashes when i try to use the compatibility mod for epic fight, here's the crash logs

The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: EC Epic Fight Compat (ec_ef_plugin) encountered an error during the sided_setup event phase
[crash-2024-11-01_21.48.03-client.txt](https://github.com/user-attachments/files/17605388/crash-2024-11-01_21.48.03-client.txt)

**Comment by userofbricks** [comment]
ah your using an epic fight version greater than 20.7.x. I have yet to get around to updating the compatibility mod to support epic fight 20.8.x or 20.9.x.

**Comment by userofbricks** [comment]
this is the same as #73 so I will close this issue and link to it from #73
