### ISSUE TITLE
NeoForge 1.21.1 Crash with ConfigData

### ISSUE THREAD

**Issue by NovaViper** [userofbricks/Expanded-Combat#79]
NeoForge v1.21.1-21.1.77
ExpanedCombat v3.3.0-beta
Curios Continuation v9.0.15+1.21.1

The game immediately crashes when I try to startup the game with just it and the Curios API included, saying `java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData`
Logs: https://mclo.gs/ZyHYGNV

**Comment by userofbricks** [comment]
your missing the required Cloth Config Api mod
