### ISSUE TITLE
Crashes on Start-up for Minecraft 1.16.5 (Forge 36.1.24)

### ISSUE THREAD

**Issue by MarioMario24680** [userofbricks/Expanded-Combat#8]
Hello, I noticed something strange happening with the Expanded Combat mod (version 2.1.2 for Minecraft 1.16.5) when I was trying to run it both client-side and server-side on Minecraft 1.16.5 (Forge 36.1.24). Although the mod doesn't cause any trouble when I try loading it alone, I noticed that as soon as I want to load other mods, it crashes immediately and doesn't give any crash report when it happens. Below is a picture of the error message that I get:
![image](https://user-images.githubusercontent.com/76149435/120016846-bb245c80-bfaa-11eb-857e-e5b0c073d57d.png)

If it helps at all, here's the client-side debug logs before the crash:
[debug.log](https://github.com/userofbricks/Expanded-Combat/files/6562285/debug.log)
Here's the server-side debug logs before the crash, in case this is any different from the client-side version:
[debug.log](https://github.com/userofbricks/Expanded-Combat/files/6562288/debug.log)

Here is a list of all of the mods that I typically use in my modpack (after testing each of them, they're all stable and functional in this version of Minecraft and Forge, so as far as I can tell, the crash isn't coming from them; the crash only happens when I include the Expanded Combat mod):
[Good Mods.txt](https://github.com/userofbricks/Expanded-Combat/files/6562304/Good.Mods.txt)

If there's any more information that you need to know, feel free to ask and I'll try to help you in the best way that I can. Please fix this whenever you have time.

**Comment by userofbricks** [comment]
expanded combat seams to conflict with the mod expandability. but only when one of the mods that depends on it is loaded. I have no idea how to find what mod depends on expandability with the curse forge website down so I'll continue when the site is back.

**Comment by userofbricks** [comment]
scratch out my last comment Iv'e been pooring over the logs a bit more and realised a mistake in which mod it was creating this error when combined with expanded combat.
the mods mod id is most likely mvw but currently I don't know what mod that is so I will continue to search. if you have any suggestions as to what mod it could have that modid please respond.

**Comment by userofbricks** [comment]
Well that didn't take long. I found the mod but I can't view its code to help fix the issue. this is the mod that is incompatable: [morevanillaweapons](https://www.curseforge.com/minecraft/mc-mods/morevanillaweapons)

**Comment by userofbricks** [comment]
Yeah I'm going to have to put this mod as an incompatability.
