### ISSUE TITLE
Really odd crash that occurs when searching for an item.

### ISSUE THREAD

**Issue by NovaViper** [userofbricks/Expanded-Combat#80]
NeoForge v1.21.1-21.1.77
ExpanedCombat v3.3.0-beta
Curios Continuation v9.0.15+1.21.1
Cloth Config v15.0.140

Immediately after getting the mod working (sorry about #79! 😅 ); there's an odd behavior that I found when trying to use the Creative menu's search function. The game just crashes as soon as I try to type anything into the menu. `Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.LivingEntity.level()" because the return value of "top.theillusivec4.curios.api.SlotContext.entity()" is null`. 😓 I'm pretty sure I included all of the dependencies this time (if not, apologizes again!)

Logs: https://mclo.gs/DNjez5i

**Comment by userofbricks** [comment]
thats really strange. I'll have to look into it, but I am running into technical difficulties with my coding environment so I will have to figure this out latter

**Comment by GitHubDazeEnd** [comment]
Having this same issue lol

**Comment by krjencik** [comment]
same here

neoforge 21.1.80 for minecraft 1.21.1
expanded_combat-1.21.1-3.3.0-beta
curios-neoforge-9.0.15+1.21.1 thats curios api continuation 
cloth-config-15.0.140-neoforge

**Comment by userofbricks** [comment]
I've got a fix for it made. I just need to find the time to post it.

**Comment by userofbricks** [comment]
uploaded this fix last week
