### ISSUE TITLE
Pickaxe mending for no reason.

### ISSUE THREAD

**Issue by megu-o** [userofbricks/Expanded-Combat#82]
Minecraft 1.21.1
Neoforge 21.1.80
Expanded Combat 3.3.0
cloth-config-15.0.140-neoforge

As the title says, **to reproduce simply mine coal with a damaged stone pickaxe.**
I tinkered with settings to see if it's possible to change that but even if I change every mending bonus to zero on all materials/weapons the bug still persists.

**Comment by userofbricks** [comment]
this will be fixed in the 3.3.2 release
