### ISSUE TITLE
Potential JEI plugin failure

### ISSUE THREAD

**Issue by Cricket742** [userofbricks/Expanded-Combat#84]
Hi, I'm having an issue not related to this mod, but in going through my logs found this error (https://pastebin.com/ZAFV9iUr) related to ecs jei plugin and thought i'd let you know. Looks like it has something to do with potion effects. Not sure if it's major or not just thought I'd let you know. And sorry in advance if this is nothing to be worried about

**Comment by userofbricks** [comment]
seems as though JEI has updated some of their item subtype code for 1.20.1. that would be very beneficial to update, but its not a change that would cause any sort of crash so it can wait a moment.

**Comment by userofbricks** [comment]
I have fixed this minor bug and the fix will come out in the next upload
