### ISSUE TITLE
When i trying to launch my server, he crashes

### ISSUE THREAD

**Issue by 003hdletsee** [userofbricks/Expanded-Combat#9]
Aternos said, that the problem is here

[09Jun2021 14:01:10.357] [main/FATAL] [net.minecraft.server.Main/]:&nbsp;Failed to start the minecraft server
--
2090 | net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
2091 | Expanded Combat (expanded_combat) has failed to load correctly
2092 | §7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/widget/Widget for invalid dist DEDICATED_SERVER
2093 | ]
2094 | at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?]
2095 | at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?]
2096 | at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?]
2097 | at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]
2098 | at net.minecraft.server.Main.main(Main.java:95) ~[?:?]
2099 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
2100 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
2101 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
2102 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
2103 | at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.1]
2104 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
2105 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
2106 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
2107 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
2108 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
2109 | at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?]
2110 | at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?]
2111 | at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?]

**Comment by userofbricks** [comment]
ah. i see the problem. somehow missed that one in testing.

**Comment by userofbricks** [comment]
I've changed quite a bit since the last update in my code so fixing this will have to wait till the next update. I wish it was easier to fix and put out a new upload but it isn't right now.

**Comment by krohs** [comment]
Yeah this happened to me also when I updated to 2.2.0

**Comment by 003hdletsee** [comment]
thank you

**Comment by CynicalShrew** [comment]
Same issues here, unfortunately. Just gonna have to leave the mod out til the next update.

**Comment by NemecRaphael** [comment]
For server:
Same issue for me using the newest mod version (2.2.0-1) with the newest forge version (36.1.32)
But found out, that the previous mod version (2.1.2-1) is still working fine on server site.

For client:
Works fine

**Comment by userofbricks** [comment]
Yeah the bug has to do with certain elements of my gui code accidentally running on the server side when it’s meant to only run client. Obviously that’s not the entirety of the gui.
